### ISSUE TITLE
RFE: Add optional tests for binder permission checks, if kernel supports it

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-testsuite#27]
Add optional tests for binder permission checks, if kernel supports it.
Not sure about this one, since it seems unlikely that Fedora would enable CONFIG_ANDROID much less the binder driver, but wouldn't hurt to include a test that could be run if enabled

**Comment by WOnder93** [comment]
Isn't this already resolved by 93df6a81b6b2264ad10aa8482d2b873ace14ef5d?
